# ---------------------------------------------------------------------------------------------------------------------
# OTC - Terraform managed File, please don't change as it will overwritten!
# ---------------------------------------------------------------------------------------------------------------------
name: 'Deploy (int)'

on:
  pull_request:


permissions:
  # required for all workflows
  # kics-scan ignore-line
  id-token: write # This is required for requesting the JWT
  security-events: write
  actions: read
  contents: write
  checks: write
  pull-requests: write

jobs:
  TF:
      name: Terraform (int)
      uses: Ontracon/gh-workflows/.github/workflows/otc-tf-deploy.yml@main
      secrets: inherit
      with:
        environment: int
